// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: signin_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignInForMailBaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mail     string `protobuf:"bytes,8,opt,name=mail,proto3" json:"mail,omitempty"`
	Password string `protobuf:"bytes,9,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *SignInForMailBaseRequest) Reset() {
	*x = SignInForMailBaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_signin_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignInForMailBaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInForMailBaseRequest) ProtoMessage() {}

func (x *SignInForMailBaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_signin_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInForMailBaseRequest.ProtoReflect.Descriptor instead.
func (*SignInForMailBaseRequest) Descriptor() ([]byte, []int) {
	return file_signin_message_proto_rawDescGZIP(), []int{0}
}

func (x *SignInForMailBaseRequest) GetMail() string {
	if x != nil {
		return x.Mail
	}
	return ""
}

func (x *SignInForMailBaseRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type SignInForMailBaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//	*SignInForMailBaseResponse_ResponseData
	//	*SignInForMailBaseResponse_Code
	Data isSignInForMailBaseResponse_Data `protobuf_oneof:"data"`
}

func (x *SignInForMailBaseResponse) Reset() {
	*x = SignInForMailBaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_signin_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignInForMailBaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInForMailBaseResponse) ProtoMessage() {}

func (x *SignInForMailBaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_signin_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInForMailBaseResponse.ProtoReflect.Descriptor instead.
func (*SignInForMailBaseResponse) Descriptor() ([]byte, []int) {
	return file_signin_message_proto_rawDescGZIP(), []int{1}
}

func (m *SignInForMailBaseResponse) GetData() isSignInForMailBaseResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *SignInForMailBaseResponse) GetResponseData() *ResponseData {
	if x, ok := x.GetData().(*SignInForMailBaseResponse_ResponseData); ok {
		return x.ResponseData
	}
	return nil
}

func (x *SignInForMailBaseResponse) GetCode() ProblemCode {
	if x, ok := x.GetData().(*SignInForMailBaseResponse_Code); ok {
		return x.Code
	}
	return ProblemCode_NoUserNameIsProvided
}

type isSignInForMailBaseResponse_Data interface {
	isSignInForMailBaseResponse_Data()
}

type SignInForMailBaseResponse_ResponseData struct {
	ResponseData *ResponseData `protobuf:"bytes,10,opt,name=responseData,proto3,oneof"`
}

type SignInForMailBaseResponse_Code struct {
	Code ProblemCode `protobuf:"varint,11,opt,name=code,proto3,enum=ProblemCode,oneof"`
}

func (*SignInForMailBaseResponse_ResponseData) isSignInForMailBaseResponse_Data() {}

func (*SignInForMailBaseResponse_Code) isSignInForMailBaseResponse_Data() {}

var File_signin_message_proto protoreflect.FileDescriptor

var file_signin_message_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4a, 0x0a, 0x18,
	0x53, 0x69, 0x67, 0x6e, 0x49, 0x6e, 0x46, 0x6f, 0x72, 0x4d, 0x61, 0x69, 0x6c, 0x42, 0x61, 0x73,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x69, 0x6c,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x7c, 0x0a, 0x19, 0x53, 0x69, 0x67, 0x6e,
	0x49, 0x6e, 0x46, 0x6f, 0x72, 0x4d, 0x61, 0x69, 0x6c, 0x42, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x0c, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x22, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x50, 0x72, 0x6f, 0x62, 0x6c,
	0x65, 0x6d, 0x43, 0x6f, 0x64, 0x65, 0x48, 0x00, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x42, 0x06,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_signin_message_proto_rawDescOnce sync.Once
	file_signin_message_proto_rawDescData = file_signin_message_proto_rawDesc
)

func file_signin_message_proto_rawDescGZIP() []byte {
	file_signin_message_proto_rawDescOnce.Do(func() {
		file_signin_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_signin_message_proto_rawDescData)
	})
	return file_signin_message_proto_rawDescData
}

var file_signin_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_signin_message_proto_goTypes = []interface{}{
	(*SignInForMailBaseRequest)(nil),  // 0: SignInForMailBaseRequest
	(*SignInForMailBaseResponse)(nil), // 1: SignInForMailBaseResponse
	(*ResponseData)(nil),              // 2: ResponseData
	(ProblemCode)(0),                  // 3: ProblemCode
}
var file_signin_message_proto_depIdxs = []int32{
	2, // 0: SignInForMailBaseResponse.responseData:type_name -> ResponseData
	3, // 1: SignInForMailBaseResponse.code:type_name -> ProblemCode
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_signin_message_proto_init() }
func file_signin_message_proto_init() {
	if File_signin_message_proto != nil {
		return
	}
	file_common_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_signin_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignInForMailBaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_signin_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignInForMailBaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_signin_message_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*SignInForMailBaseResponse_ResponseData)(nil),
		(*SignInForMailBaseResponse_Code)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_signin_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_signin_message_proto_goTypes,
		DependencyIndexes: file_signin_message_proto_depIdxs,
		MessageInfos:      file_signin_message_proto_msgTypes,
	}.Build()
	File_signin_message_proto = out.File
	file_signin_message_proto_rawDesc = nil
	file_signin_message_proto_goTypes = nil
	file_signin_message_proto_depIdxs = nil
}
